### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by anuragsr** [spite/THREE.MeshLine#154]
The links given for examples do not work.. just a blank screen appears with the page title and GUI if applicable

**Comment by anuragsr** [comment]
The [Birds](http://spite.github.io/THREE.MeshLine/demo/birds.html) example seems to work

**Comment by microdee** [comment]
> The [Birds](http://spite.github.io/THREE.MeshLine/demo/birds.html) example seems to work

but the lines are not there, as on the screenshot either

**Comment by savejeff** [comment]
examples still do not work. console gives error: 
```

Uncaught TypeError: g.getAttribute is not a function
    at MeshLine.setGeometry (THREE.MeshLine.js:81:26)
    at makeLine (main-graph.js:47:4)
    at createLines (main-graph.js:76:2)
    at init (main-graph.js:64:2)
    at main-graph.js:41:1
```

**Comment by 002301** [comment]
modify THREE.MeshLine.js:81 to
    // this.setPoints(g.getAttribute("position").array, c);
    if (g instanceof THREE.Geometry) {
      this.setPoints(g.vertices, c);
    } else if (g instanceof THREE.BufferGeometry) {
      this.setPoints(g.getAttribute("position").array, c);
    } else {
      this.setPoints(g, c);
    }

**Comment by savejeff** [comment]
Thx. would it be possible to update the Demos/Examples? 
They currently still do not work

**Comment by ActuallyHappening** [comment]
Still doesn't work, exact error as above

**Comment by POKEZHANG** [comment]
> modify THREE.MeshLine.js:81 to // this.setPoints(g.getAttribute("position").array, c); if (g instanceof THREE.Geometry) { this.setPoints(g.vertices, c); } else if (g instanceof THREE.BufferGeometry) { this.setPoints(g.getAttribute("position").array, c); } else { this.setPoints(g, c); }

ok,it's work
